# Generated by Django 5.1.7 on 2025-03-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('users', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.userprofile'),
        ),
    ]
